services:
  mariadba3:
    image: mariadb
    container_name: mariadba3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: ciber
    volumes:
      - mariadb_dataa3:/var/lib/mysql
      - ./Clases.sql://docker-entrypoint-initdb.d/Clases.sql:ro
    user: mysql
  phpmyadmina3:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadba3
    ports:
      - 7003:80
    depends_on:
      - mariadba3

  pythona3:
    build: ./api
    container_name: pythona3
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: ciber
      DB_HOST: mariadba3
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - mariadba3
    restart: unless-stopped

  apachea3:
    build: ./apache
    ports:
      - 6003:80
    depends_on:
      - pythona3
    links:
      - pythona3
    restart: unless-stopped
volumes:
  mariadb_dataa3:
